spring:
    application:
        name: oauth-test
    profiles:
        active: local
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
        username: root
        password: 1234
    liquibase:
        enabled: true
        dropFirst: false
    h2:
        console:
            enabled: true